name: shuban
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

  gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 4983:4983
    volumes:
      - gateway_data:/app

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/data

volumes:
  gateway_data:
  postgres_data:
